export const data = [
  {
    name: "Bitcoin",
    symbol: "BTC",
    img: "https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=024",
    price: 31812.8,
    change: +10,
    tvl: 60000,
    popular: [
      "https://cryptologos.cc/logos/solana-sol-logo.svg?v=024",
      "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=024",
      "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    ],
  },
  {
    name: "Solana",
    symbol: "sol",
    img: "https://cryptologos.cc/logos/solana-sol-logo.svg?v=024",
    price: 32.83,
    change: -12.32,
    tvl: 60000,
    popular: [
      "https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=024",
      "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=024",
      "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    ],
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    img: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=024",
    price: 1466.45,
    change: -11.93,
    tvl: 60000,
    popular: [
      "https://cryptologos.cc/logos/solana-sol-logo.svg?v=024",
      "https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=024",
      "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    ],
  },
  {
    name: "Binance USD",
    symbol: "BUSD",
    img: "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    price: 1,
    change: +0.26,
    tvl: 60000,
    popular: [
      "https://cryptologos.cc/logos/solana-sol-logo.svg?v=024",
      "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=024",
      "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    ],
  },
  {
    name: "Shiba Inu",
    symbol: "SHIB",
    img: "https://cryptologos.cc/logos/shiba-inu-shib-logo.svg?v=024",
    price: 0.00000001948,
    change: -8.1,
    tvl: 60000,
    popular: [
      "https://cryptologos.cc/logos/solana-sol-logo.svg?v=024",
      "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=024",
      "https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=024",
    ],
  },
];
