export const data = [
  {
    name: "Bitcoin",
    symbol: "BTC",
    img: "",
    price: 31812.8,
    change: +10,
    tvl: 60000,
    popular: ["SOL", "ETH", "BUSD"],
  },
  {
    name: "Solana",
    symbol: "SOL",
    img: "",
    price: 32.83,
    change: -12.32,
    tvl: 60000,
    popular: ["BTC", "ETH", "BUSD"],
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    img: "",
    price: 1466.45,
    change: -11.93,
    tvl: 60000,
    popular: ["SOL", "BTC", "BUSD"],
  },
  {
    name: "Binance USD",
    symbol: "BUSD",
    img: "",
    price: 1,
    change: +0.26,
    tvl: 60000,
    popular: ["SOL", "ETH", "BUSD"],
  },
  {
    name: "Shiba Inu",
    symbol: "SHIB",
    img: "",
    price: 0.00000001948,
    change: -8.1,
    tvl: 60000,
    popular: ["SOL", "ETH", "BUSD"],
  },
];
